In [ ]:
import pandas as pd  
import csv
from sklearn.model_selection import train_test_split # ფუქნცია რომელიც მონაცემებს დაჰყოფს train/test-ად.
pd.set_option("display.max_colwidth", None)

In [ ]:
df = pd.read_csv(
    "../data/SMSSpamCollection",  
    sep="\t",                 
    header=None,              
    names=["label", "text"],  
    quoting=csv.QUOTE_NONE,    
)

In [ ]:
df.shape # rows and columns

(5574, 2)

In [5]:
df.head()

,label,text
0,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives around here though"

In [7]:
df["label"].value_counts()

label
ham     4827
spam     747
Name: count, dtype: int64

In [8]:
df["label"].value_counts(normalize=True)

label
ham     0.865985
spam    0.134015
Name: proportion, dtype: float64

In [9]:
df.duplicated().sum()

np.int64(403)

In [11]:
df = df.drop_duplicates()

df = df.reset_index(drop=True)

df.shape

(5171, 2)

In [12]:
df["label"].value_counts(normalize=True)

label
ham     0.873719
spam    0.126281
Name: proportion, dtype: float64

In [13]:
df["length"] = df["text"].str.len()

df.groupby("label")["length"].mean()

label
ham      70.894865
spam    137.710567
Name: length, dtype: float64

In [16]:
df["y"] = df["label"].map({"ham": 0, "spam" : 1})

df.head()

,label,text,length,y
0,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",111,0
1,ham,Ok lar... Joking wif u oni...,29,0
2,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,155,1
3,ham,U dun say so early hor... U c already then say...,49,0
4,ham,"Nah I don't think he goes to usf, he lives around here though",61,0

In [20]:
X = df["text"]
y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42,
)

len(X_train),len(X_test)

(4136, 1035)

In [21]:
print("Train:")
print(y_train.value_counts(normalize=True))
print()
print("Test:")
print(y_test.value_counts(normalize=True))

Train:
y
0    0.873791
1    0.126209
Name: proportion, dtype: float64

Test:
y
0    0.87343
1    0.12657
Name: proportion, dtype: float64

In [30]:
train_df = pd.DataFrame({"text": X_train, "y": y_train})
test_df = pd.DataFrame({"text": X_test, "y" : y_test})

is_spam = train_df["y"] == 1

train_df[is_spam].sample(20, random_state=42)

,text,y
1172,WIN a year supply of CDs 4 a store of ur choice worth £500 & enter our £100 Weekly draw txt MUSIC to 87066 Ts&Cs www.Ldew.com.subs16+1win150ppmx3,1
4716,Free video camera phones with Half Price line rental for 12 mths and 500 cross ntwk mins 100 txts. Call MobileUpd8 08001950382 or Call2OptOut/674,1
2035,You are a winner you have been specially selected to receive £1000 cash or a £2000 award. Speak to a live operator to claim call 087123002209am-7pm. Cost 10p,1
4991,dating:i have had two of these. Only started after i sent a text to talk sport radio last week. Any connection do you think or coincidence?,1
2124,"URGENT!! Your 4* Costa Del Sol Holiday or £5000 await collection. Call 09050090044 Now toClaim. SAE, TC s, POBox334, Stockport, SK38xh, Cost£1.50/pm, Max10mins",1
4613,"Hi this is Amy, we will be sending you a free phone number in a couple of days, which will give you an access to all the adult parties...",1
5058,You have won a guaranteed 32000 award or maybe even £1000 cash to claim ur award call free on 0800 ..... (18+). Its a legitimat efreefone number wat do u think???,1
1269,Enjoy the jamster videosound gold club with your credits for 2 new videosounds+2 logos+musicnews! get more fun from jamster.co.uk! 16+only Help? call: 09701213186,1
1816,U have a secret admirer who is looking 2 make contact with U-find out who they R*reveal who thinks UR so special-call on 09058094594,1
1047,URGENT! We are trying to contact U. Todays draw shows that you have won a £800 prize GUARANTEED. Call 09050003091 from land line. Claim C52. Valid12hrs only,1
3752,(Bank of Granite issues Strong-Buy) EXPLOSIVE PICK FOR OUR MEMBERS *****UP OVER 300% *********** Nasdaq Symbol CDGT That is a $5.00 per..,1
2568,URGENT! We are trying to contact U. Todays draw shows that you have won a £800 prize GUARANTEED. Call 09050003091 from land line. Claim C52. Valid 12hrs only,1
305,"TheMob> Check out our newest selection of content, Games, Tones, Gossip, babes and sport, Keep your mobile fit and funky text WAP to 82468",1
4835,Our records indicate u maybe entitled to 5000 pounds in compensation for the Accident you had. To claim 4 free reply with CLAIM to this msg. 2 stop txt STOP,1
519,"Today's Offer! Claim ur £150 worth of discount vouchers! Text YES to 85023 now! SavaMob, member offers mobile! T Cs 08717898035. £3.00 Sub. 16 . Unsub reply X",1
3392,Do you want a New Nokia 3510i Colour Phone Delivered Tomorrow? With 200 FREE minutes to any mobile + 100 FREE text + FREE camcorder Reply or Call 08000930705,1
4617,"Welcome to Select, an O2 service with added benefits. You can now call our specially trained advisors FREE from your mobile by dialling 402.",1
2592,Hope you enjoyed your new content. text stop to 61610 to unsubscribe. help:08712400602450p Provided by tones2you.co.uk,1
598,XCLUSIVE@CLUBSAISAI 2MOROW 28/5 SOIREE SPECIALE ZOUK WITH NICHOLS FROM PARIS.FREE ROSES 2 ALL LADIES !!! info: 07946746291/07880867867,1
2479,Join the UK's horniest Dogging service and u can have sex 2nite!. Just sign up and follow the instructions. Txt ENTRY to 69888 now! Nyt.EC2A.3LP.msg@150p,1

In [ ]:
train_df[~is_spam].sample(20, random_state=42)

,text,y
5075,U GOIN OUT 2NITE?,0
1416,"Yalru lyfu astne chikku.. Bt innu mundhe lyf ali halla ke bilo (marriage)program edhae, so lyf is nt yet ovr chikku..ali vargu lyfu meow meow:-D",0
3170,Sorry i cant take your call right now. It so happens that there r 2waxsto do wat you want. She can come and ill get her medical insurance. And she'll be able to deliver and have basic care. I'm currently shopping for the right medical insurance for her. So just give me til friday morning. Thats when i.ll see the major person that can guide me to the right insurance.,0
4698,Thanks for being there for me just to talk to on saturday. You are very dear to me. I cherish having you as a brother and role model.,0
2147,Nothing just getting msgs by dis name wit different no's..,0
4471,Yup. Izzit still raining heavily cos i'm in e mrt i can't c outside.,0
2963,Good evening! this is roger. How are you?,0
4491,E admin building there? I might b slightly earlier... I'll call u when i'm reaching...,0
3150,Sac will score big hundred.he is set batsman:-),0
3018,MAYBE IF YOU WOKE UP BEFORE FUCKING 3 THIS WOULDN'T BE A PROBLEM.,0
3741,Reason is if the team budget is available at last they buy the unsold players for at base rate..,0
882,How is it possible to teach you. And where.,0
2527,Pandy joined 4w technologies today.he got job..,0
2213,Should I tell my friend not to come round til like &lt;#&gt; ish?,0
2337,Btw regarding that we should really try to see if anyone else can be our 4th guy before we commit to a random dude,0
366,I'm going for bath will msg you next &lt;#&gt; min..,0
1680,Why tired what special there you had,0
872,Why do you ask princess?,0
4128,You also didnt get na hi hi hi hi hi,0
1482,I think chennai well settled?,0
3408,No. I.ll meet you in the library,0
2211,"&lt;#&gt; , that's all? Guess that's easy enough",0
2164,I am getting threats from your sales executive Shifad as i raised complaint against him. Its an official message.,0
4271,But you were together so you should be thinkin about him,0
4479,Just come home. I don't want u to be miserable,0
478,If we win its really no 1 side for long time.,0
689,K..u also dont msg or reply to his msg..,0
2529,"They can try! They can get lost, in fact. Tee hee",0
2074,What year. And how many miles.,0
4287,Noooooooo please. Last thing I need is stress. For once in your life be fair.,0
0,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",0
1945,From tomorrow onwards eve 6 to 3 work.,0
212,Sounds great! Are you home now?,0
3746,Nationwide auto centre (or something like that) on Newport road. I liked them there,0
26,Lol your always so convincing.,0
2152,Think you sent the text to the home phone. That cant display texts. If you still want to send it his number is,0
1623,Nah dub but je still buff,0
1437,Purity of friendship between two is not about smiling after reading the forwarded message..Its about smiling just by seeing the name. Gud evng musthu,0
3825,Ok i wont call or disturb any one. I know all are avoiding me. I am a burden for all,0
2503,2marrow only. Wed at &lt;#&gt; to 2 aha.,0

In [26]:
train_df.to_csv("../data/train.csv", index=False)
test_df.to_csv("../data/test.csv", index=False)

In [27]:
pd.read_csv("../data/test.csv").head()

,text,y
0,"Aight, I should be there by 8 at the latest, probably closer to 7. Are jay and tyler down or should we just do two trips?",0
1,Its ok my arm is feeling weak cuz i got a shot so we can go another time,0
2,Ladies first and genus second k .,0
3,Neva mind it's ok..,0
4,Todays Vodafone numbers ending with 4882 are selected to a receive a £350 award. If your number matches call 09064019014 to receive your £350 award.,1